version: "3.6"
services:
  app:
    container_name: app
    image: autotune:latest
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - 8000:8000
    restart: always
    env_file:
      - ./.env
