# Generated by Django 4.2.10 on 2024-03-16 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_workflows_dataset_alter_workflows_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examples',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='workflow.workflows'),
        ),
    ]
