# Generated by Django 4.2.11 on 2024-04-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_task_total_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examples',
            name='text',
            field=models.JSONField(default=dict),
        ),
    ]
