# Generated by Django 4.2.11 on 2024-04-10 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0006_alter_examples_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='total_number',
        ),
        migrations.AlterField(
            model_name='task',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='workflow.workflows'),
        ),
    ]
