# Generated by Django 4.2.11 on 2024-04-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0007_remove_task_total_number_alter_task_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='examples',
            name='task_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
