# Generated by Django 4.2.11 on 2024-04-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_examples_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='temp_data',
        ),
        migrations.AlterField(
            model_name='workflows',
            name='status',
            field=models.CharField(choices=[('SETUP', 'Setup'), ('ITERATION', 'Iteration'), ('GENERATION', 'Generation'), ('TRAINING', 'Training'), ('PUSHING_DATASET', 'Pushing Dataset'), ('PUSHING_MODEL', 'Pushing Model'), ('IDLE', 'Idle')], default='SETUP', max_length=20),
        ),
    ]
