# Generated by Django 4.2.11 on 2024-04-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_remove_workflows_workflow_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowconfig',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
