# Generated by Django 4.2.11 on 2024-04-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0012_alter_workflowconfig_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workflowconfig",
            name="json_schema",
        ),
        migrations.AddField(
            model_name="workflowconfig",
            name="fields",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="workflowconfig",
            name="model_string",
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="workflowconfig",
            name="schema_example",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="workflows",
            name="llm_model",
            field=models.CharField(
                choices=[
                    ("gpt-4-0125-preview", "gpt-4-0125-preview"),
                    ("gpt-4-turbo", "gpt-4-turbo"),
                    ("gpt-4-turbo-preview", "gpt-4-turbo-preview"),
                    ("gpt-4-1106-preview", "gpt-4-1106-preview"),
                    ("gpt-4-vision-preview", "gpt-4-vision-preview"),
                    ("gpt-3.5-turbo-0125", "gpt-3.5-turbo-0125"),
                    ("gpt-3.5-turbo", "gpt-3.5-turbo"),
                ],
                max_length=255,
            ),
        ),
    ]
