# Generated by Django 4.2.11 on 2024-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0015_remove_workflowconfig_parameters_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
