# Generated by Django 4.2.11 on 2024-05-02 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0016_user_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prompt",
            name="user",
        ),
        migrations.AddField(
            model_name="prompt",
            name="system_prompt",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prompt",
            name="user_prompt",
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
