# Generated by Django 4.2.11 on 2024-05-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0017_remove_prompt_user_prompt_system_prompt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflows",
            name="cost",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="workflows",
            name="estimated_dataset_cost",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="workflows",
            name="llm_model",
            field=models.CharField(
                choices=[
                    ("gpt-4-0125-preview", "gpt-4-0125-preview"),
                    ("gpt-4-1106-preview", "gpt-4-1106-preview"),
                    ("gpt-4-vision-preview", "gpt-4-vision-preview"),
                    ("gpt-3.5-turbo-1106", "gpt-3.5-turbo-1106"),
                    ("gpt-3.5-turbo-0613", "gpt-3.5-turbo-0613"),
                    ("gpt-3.5-turbo-16k-0613", "gpt-3.5-turbo-16k-0613"),
                    ("gpt-3.5-turbo-0125", "gpt-3.5-turbo-0125"),
                    ("gpt-3.5-turbo-0301", "gpt-3.5-turbo-0301"),
                    ("gpt-3.5-turbo", "gpt-3.5-turbo"),
                ],
                max_length=255,
            ),
        ),
    ]
