# Generated by Django 4.2.11 on 2024-05-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0020_alter_dataset_latest_commit_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(default="user", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="huggingface_user_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
