# Generated by Django 4.2.11 on 2024-05-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0021_user_role_alter_user_huggingface_user_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trained_at", models.DateTimeField(auto_now_add=True)),
                ("logs", models.JSONField(default=dict)),
                ("metrics", models.JSONField(default=dict)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="workflow.mlmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training",
                        to="workflow.user",
                    ),
                ),
            ],
        ),
    ]
