# Generated by Django 4.2.13 on 2024-06-04 01:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0022_trainingmetadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetCreationTask",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("status", models.CharField(max_length=20)),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dataset_creation_tasks",
                        to="workflow.workflows",
                    ),
                ),
            ],
        ),
    ]
