# Generated by Django 4.2.13 on 2024-05-30 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0023_dataset_type_workflows_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodel",
            name="label_studio_comp",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="label_studio_component",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="rendering_config",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="trained_on",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trained_on",
                to="workflow.dataset",
            ),
        ),
    ]
