# Generated by Django 4.2.13 on 2024-05-31 12:15

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import workflow.models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0025_datasetdata_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workflows",
            name="llm_model",
            field=models.CharField(
                choices=[
                    ("gpt-4-0125-preview", "gpt-4-0125-preview"),
                    ("gpt-4-1106-preview", "gpt-4-1106-preview"),
                    ("gpt-4-vision-preview", "gpt-4-vision-preview"),
                    ("gpt-3.5-turbo-1106", "gpt-3.5-turbo-1106"),
                    ("gpt-3.5-turbo-0613", "gpt-3.5-turbo-0613"),
                    ("gpt-3.5-turbo-16k-0613", "gpt-3.5-turbo-16k-0613"),
                    ("gpt-3.5-turbo-0125", "gpt-3.5-turbo-0125"),
                    ("gpt-3.5-turbo-0301", "gpt-3.5-turbo-0301"),
                    ("gpt-3.5-turbo", "gpt-3.5-turbo"),
                ],
                default="gpt-3.5-turbo",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="workflows",
            name="split",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    validators=[
                        django.core.validators.MinValueValidator(0),
                        django.core.validators.MaxValueValidator(100),
                    ]
                ),
                blank=True,
                default=workflow.models.default_split,
                null=True,
                size=None,
                validators=[workflow.models.validate_split],
            ),
        ),
        migrations.AlterField(
            model_name="workflows",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="workflows",
            name="total_examples",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
