# Generated by Django 4.2.13 on 2024-07-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0028_mlmodel_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="mlmodel",
            name="deployed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
