# Generated by Django 4.2.13 on 2024-07-01 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0029_mlmodel_deployed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainingmetadata",
            name="user",
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ml_model",
                to="workflow.user",
            ),
            preserve_default=False,
        ),
    ]
