# Generated by Django 4.2.13 on 2024-07-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0030_remove_trainingmetadata_user_mlmodel_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mlmodel",
            name="label_studio_comp",
        ),
        migrations.RemoveField(
            model_name="mlmodel",
            name="label_studio_component",
        ),
        migrations.RemoveField(
            model_name="mlmodel",
            name="rendering_config",
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="label_studio_element",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mlmodel",
            name="telemetry_data_field",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
