# Generated by Django 4.2.13 on 2024-07-01 08:44

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0033_mlmodel_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetdata",
            name="record_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="datasetdata",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="workflow.user",
            ),
            preserve_default=False,
        ),
    ]
